# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_gsi_enums.py
# Compiled at: 2017-02-14 19:17:14
# Size of source mod 2**32: 829 bytes
import enum

class AutonomyStageLabel:
    BEFORE_TESTS = '1 - Before Tests'
    AFTER_TESTS = '2 - After Tests'
    BEFORE_POSTURE_SEARCH = '3 - Before Posture Search'
    AFTER_POSTURE_SEARCH = '4 - After Posture Search'
    AFTER_SCORING = '5 - After Scoring'


class GSIDataKeys(enum.Int, export=False):
    AFFORDANCE_KEY = ...
    PROBABILITY_KEY = ...
    OBJECTS_KEY = ...
    COMMODITIES_KEY = ...
    REQUEST_KEY = ...
    MIXER_PROVIDER_KEY = ...
    MIXER_SELECTED_KEY = ...
    MIXERS_KEY = ...
    MIXER_CACHING_INFO_KEY = ...
    ADDITIONAL_RESULT_INFO = ...