# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: T:\InGame\Gameplay\Scripts\Server\objects\components\state_change.py
# Compiled at: 2020-09-29 21:23:50
# Size of source mod 2**32: 1735 bytes


class StateChange:
    VFX = 'vfx_state'
    VFX_STATE = 'vfx_state_state'
    AUDIO_STATE = 'audio_state'
    AUDIO_EFFECT_STATE = 'audio_effect_state'
    AUTONOMY_MODIFIERS = 'autonomy_modifiers'
    AWARENESS = 'awareness'
    BROADCASTER = 'broadcaster'
    ENVIRONMENT_SCORE = 'environment_score'
    PAINTING_REVEAL_LEVEL = 'painting_reveal_level'
    PAINTING_STATE = 'painting_state'
    FLOWING_PUDDLE_ENABLED = 'flowing_puddle_enabled'
    REPLACE_OBJECT = 'replace_object'
    UI_METADATA = 'ui_metadata'
    VIDEO_STATE = 'video_playlist'
    VIDEO_STATE_LOOPING = 'video_playlist_looping'
    LIGHT_DIMMER_STATE = 'light_dimmer'
    LIGHT_MATERIAL_STATE = 'light_material_states'
    LIGHT_HAUNTED_STATE = 'light_haunted_state'
    LOT_MODIFIERS = 'lot_statistic_modifiers'
    SINGED = 'singed'
    WIND_SPEED_LEVEL = 'wind_speed_level'
    GRUBBY = 'grubby'
    SCRATCHED = 'scratched'
    CHANGE_VALUE = 'change_value'
    TOGGLE_FOOTPRINT = 'toggle_footprint'
    MANNEQUIN_POSE = 'mannequin_pose'
    GEOMETRY_STATE_OVERRIDE = 'geometry_state_override'
    MODEL_SUITE_STATE_INDEX = 'model_suite_state_index'
    UTILITY_MODIFIERS = 'utility_modifiers'
    LIVE_DRAG = 'live_drag_state'
    FOCUS_SCORE = 'focus_score'
    WALKSTYLE = 'walkstyle'
    PERIODIC_LOOT = 'periodic_loot'
    GLOW = 'glow'
    SITUATION = 'situation'
    TAN_LEVEL = 'tan_level'
    ROUTE_EVENT = 'route_event'
    SET_FIRE = 'set_fire'
    SCALE = 'scale'
    DYED = 'dyed'
    VOICE_ACTOR = 'voice_actor'